"""budgets_whatsapp

Revision ID: 3ea6512191ab
Revises: 933f3d3e65f4
Create Date: 2026-09-22 12:54:55.922224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3ea6512191ab'
down_revision: Union[str, Sequence[str], None] = '933f3d3e65f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount_brl', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('block_on_exceed', sa.Boolean(), nullable=False),
    sa.Column('alert_at', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_org_id'), ['org_id'], unique=False)

    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_messages', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_cost_usd', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_split', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_split')
        batch_op.drop_column('whatsapp_cost_usd')
        batch_op.drop_column('whatsapp_messages')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_org_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_created_at'))

    op.drop_table('budgets')
    # ### end Alembic commands ###
