"""add ruflo patterns: agent knowledge/learning/reflection, swarm config/task/message, sparc workflow, learning jobs

Revision ID: 5def150444e3
Revises: h4b5c6d7e8f9
Create Date: 2026-09-14 00:14:52.212414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5def150444e3'
down_revision: Union[str, Sequence[str], None] = 'h4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_knowledge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_type', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_knowledge_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_knowledge_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_knowledge_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_knowledge_org_id'), ['org_id'], unique=False)

    op.create_table('agent_learnings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('learning_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_context', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('pattern_signature', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('applied_count', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_learnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_learnings_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_learnings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_learnings_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_learnings_pattern_signature'), ['pattern_signature'], unique=False)

    op.create_table('learning_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('input_config', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cron_expr', sa.String(length=100), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_jobs_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_jobs_org_id'), ['org_id'], unique=False)

    op.create_table('optimization_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('optimization_type', sa.String(length=50), nullable=False),
    sa.Column('target_metric', sa.String(length=50), nullable=False),
    sa.Column('before_value', sa.Float(), nullable=False),
    sa.Column('after_value', sa.Float(), nullable=False),
    sa.Column('improvement_pct', sa.Float(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('change_details', sa.JSON(), nullable=False),
    sa.Column('validation_method', sa.String(length=50), nullable=False),
    sa.Column('validation_score', sa.Float(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_records_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_records_org_id'), ['org_id'], unique=False)

    op.create_table('sparc_workflows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_phase', sa.String(length=30), nullable=False),
    sa.Column('phase_status', sa.String(length=20), nullable=False),
    sa.Column('spec_output', sa.JSON(), nullable=False),
    sa.Column('pseudocode_output', sa.JSON(), nullable=False),
    sa.Column('architect_output', sa.JSON(), nullable=False),
    sa.Column('refine_output', sa.JSON(), nullable=False),
    sa.Column('code_output', sa.JSON(), nullable=False),
    sa.Column('test_output', sa.JSON(), nullable=False),
    sa.Column('refactor_output', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sparc_workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sparc_workflows_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sparc_workflows_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sparc_workflows_org_id'), ['org_id'], unique=False)

    op.create_table('sparc_phase_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sparc_workflow_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('phase', sa.String(length=30), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('input_context', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sparc_workflow_id'], ['sparc_workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sparc_phase_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sparc_phase_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sparc_phase_logs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sparc_phase_logs_sparc_workflow_id'), ['sparc_workflow_id'], unique=False)

    op.create_table('team_swarm_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('swarm_mode', sa.String(length=30), nullable=False),
    sa.Column('leader_election', sa.String(length=30), nullable=False),
    sa.Column('leader_agent_id', sa.String(length=36), nullable=True),
    sa.Column('leadership_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('task_distribution', sa.String(length=30), nullable=False),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('task_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('consensus_threshold', sa.Float(), nullable=False),
    sa.Column('consensus_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('broadcast_enabled', sa.Boolean(), nullable=False),
    sa.Column('shared_memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('shared_memory_ttl_hours', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('failure_escalation', sa.String(length=30), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['leader_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_swarm_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_swarm_configs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_swarm_configs_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_swarm_configs_team_id'), ['team_id'], unique=True)

    op.create_table('crm_deal_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deal_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('changed_by', sa.String(length=36), nullable=True),
    sa.Column('changed_by_type', sa.String(length=20), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['crm_deals.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crm_deal_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crm_deal_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deal_versions_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deal_versions_org_id'), ['org_id'], unique=False)

    op.create_table('agent_reflections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('task_summary', sa.Text(), nullable=False),
    sa.Column('what_went_well', sa.Text(), nullable=False),
    sa.Column('what_could_improve', sa.Text(), nullable=False),
    sa.Column('key_insight', sa.Text(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_reflections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_reflections_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_reflections_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_reflections_org_id'), ['org_id'], unique=False)

    op.create_table('swarm_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('consensus_votes', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swarm_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swarm_tasks_assigned_agent_id'), ['assigned_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_tasks_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_tasks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_tasks_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_tasks_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_tasks_team_id'), ['team_id'], unique=False)

    op.create_table('voice_recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('call_sid', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('channel_connection_id', sa.String(length=36), nullable=True),
    sa.Column('from_number', sa.String(length=50), nullable=False),
    sa.Column('to_number', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_storage_path', sa.String(length=500), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_status', sa.String(length=20), nullable=False),
    sa.Column('transcript_language', sa.String(length=10), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['channel_connection_id'], ['channel_connections.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voice_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voice_recordings_call_sid'), ['call_sid'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_recordings_channel_connection_id'), ['channel_connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_recordings_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_recordings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_voice_recordings_org_id'), ['org_id'], unique=False)

    op.create_table('swarm_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('swarm_task_id', sa.String(length=36), nullable=True),
    sa.Column('sender_agent_id', sa.String(length=36), nullable=True),
    sa.Column('recipient_agent_id', sa.String(length=36), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('memory_key', sa.String(length=255), nullable=True),
    sa.Column('memory_ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('read_by', sa.JSON(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['recipient_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['swarm_task_id'], ['swarm_tasks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swarm_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swarm_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_messages_memory_key'), ['memory_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_messages_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_messages_recipient_agent_id'), ['recipient_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_messages_sender_agent_id'), ['sender_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_messages_swarm_task_id'), ['swarm_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swarm_messages_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_foreign_key('fk_agent_instances_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('agent_metrics', schema=None) as batch_op:
        batch_op.alter_column('messages',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('errors',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('avg_response_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tool_calls',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('system_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('llm_config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('tools',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('memory_config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('governance_config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('change_note',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('llm_config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('system_prompt',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('tools',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('memory_config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('automation_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_triggers_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('channel_connections', schema=None) as batch_op:
        batch_op.alter_column('config',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credentials_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('close_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('probability', sa.Float(), nullable=False))
        batch_op.create_index(batch_op.f('ix_crm_deals_close_date'), ['close_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_crm_deals_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('cases',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_datasets_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dead_letters_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.alter_column('judge_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('avg_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('results',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_eval_runs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_foreign_key('fk_memories_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_foreign_key('fk_messages_org', 'organizations', ['org_id'], ['id'])

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('white_label', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('custom_domain', sa.String(length=255), nullable=True))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_unique_constraint('uq_organizations_custom_domain', ['custom_domain'])

    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handoff_config', sa.JSON(), nullable=False))
        batch_op.alter_column('routing_strategy',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('input_schema',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('output_schema',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('code_reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('is_builtin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('workflow_execution_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_execution_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('tool_args',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('depends_on',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('output_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('position',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('on_failure',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workflow_nodes_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('inputs',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('outputs',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('node_status',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('error',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost_usd',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_workflows_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_created_at'))
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_created_at'))
        batch_op.alter_column('cost_usd',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('error',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('node_status',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('outputs',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('inputs',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_nodes_created_at'))
        batch_op.alter_column('retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('on_failure',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('position',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('timeout_seconds',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('output_key',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('depends_on',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('tool_args',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('workflow_execution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_execution_logs_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('is_builtin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('code_reference',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('output_schema',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('input_schema',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('routing_strategy',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('handoff_config')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_created_at'))

    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_actions_created_at'))

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_constraint('uq_organizations_custom_domain', type_='unique')
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.drop_column('custom_domain')
        batch_op.drop_column('white_label')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_org', type_='foreignkey')
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_memories_org', type_='foreignkey')
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('eval_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_runs_created_at'))
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('results',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('avg_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('judge_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('dead_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dead_letters_created_at'))

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_created_at'))
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('cases',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('crm_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deals_created_at'))
        batch_op.drop_index(batch_op.f('ix_crm_deals_close_date'))
        batch_op.drop_column('probability')
        batch_op.drop_column('close_date')

    with op.batch_alter_table('credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credentials_created_at'))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('channel',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('channel_connections', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('config',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('automation_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_triggers_created_at'))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('memory_config',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('tools',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('system_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('llm_config',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_created_at'))
        batch_op.alter_column('change_note',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('agent_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('governance_config',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('memory_config',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('tools',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('llm_config',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('system_prompt',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('agent_metrics', schema=None) as batch_op:
        batch_op.alter_column('tool_calls',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('avg_response_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('errors',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('messages',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('agent_instances', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_instances_org', type_='foreignkey')
        batch_op.alter_column('extra_data',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('swarm_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swarm_messages_team_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_messages_swarm_task_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_messages_sender_agent_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_messages_recipient_agent_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_messages_org_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_messages_memory_key'))
        batch_op.drop_index(batch_op.f('ix_swarm_messages_created_at'))

    op.drop_table('swarm_messages')
    with op.batch_alter_table('voice_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voice_recordings_org_id'))
        batch_op.drop_index(batch_op.f('ix_voice_recordings_created_at'))
        batch_op.drop_index(batch_op.f('ix_voice_recordings_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_voice_recordings_channel_connection_id'))
        batch_op.drop_index(batch_op.f('ix_voice_recordings_call_sid'))

    op.drop_table('voice_recordings')
    with op.batch_alter_table('swarm_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swarm_tasks_team_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_tasks_task_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_tasks_org_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_tasks_created_at'))
        batch_op.drop_index(batch_op.f('ix_swarm_tasks_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_swarm_tasks_assigned_agent_id'))

    op.drop_table('swarm_tasks')
    with op.batch_alter_table('agent_reflections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_reflections_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_reflections_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_reflections_agent_id'))

    op.drop_table('agent_reflections')
    with op.batch_alter_table('crm_deal_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crm_deal_versions_org_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deal_versions_deal_id'))
        batch_op.drop_index(batch_op.f('ix_crm_deal_versions_created_at'))

    op.drop_table('crm_deal_versions')
    with op.batch_alter_table('team_swarm_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_swarm_configs_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_swarm_configs_org_id'))
        batch_op.drop_index(batch_op.f('ix_team_swarm_configs_created_at'))

    op.drop_table('team_swarm_configs')
    with op.batch_alter_table('sparc_phase_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sparc_phase_logs_sparc_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_sparc_phase_logs_org_id'))
        batch_op.drop_index(batch_op.f('ix_sparc_phase_logs_created_at'))

    op.drop_table('sparc_phase_logs')
    with op.batch_alter_table('sparc_workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sparc_workflows_org_id'))
        batch_op.drop_index(batch_op.f('ix_sparc_workflows_created_at'))
        batch_op.drop_index(batch_op.f('ix_sparc_workflows_agent_id'))

    op.drop_table('sparc_workflows')
    with op.batch_alter_table('optimization_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_records_org_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_optimization_records_agent_id'))

    op.drop_table('optimization_records')
    with op.batch_alter_table('learning_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_jobs_org_id'))
        batch_op.drop_index(batch_op.f('ix_learning_jobs_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_learning_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_jobs_agent_id'))

    op.drop_table('learning_jobs')
    with op.batch_alter_table('agent_learnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_learnings_pattern_signature'))
        batch_op.drop_index(batch_op.f('ix_agent_learnings_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_learnings_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_learnings_agent_id'))

    op.drop_table('agent_learnings')
    with op.batch_alter_table('agent_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_org_id'))
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_key'))
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_knowledge_agent_id'))

    op.drop_table('agent_knowledge')
    # ### end Alembic commands ###
