"""integration_nonces_events

Revision ID: 933f3d3e65f4
Revises: ee188fe33d7f
Create Date: 2026-09-22 11:09:35.734452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '933f3d3e65f4'
down_revision: Union[str, Sequence[str], None] = 'ee188fe33d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_events',
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('peer', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    with op.batch_alter_table('integration_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_events_expires_at'), ['expires_at'], unique=False)

    op.create_table('integration_nonces',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('peer', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('nonce')
    )
    with op.batch_alter_table('integration_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integration_nonces_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('integration_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_nonces_expires_at'))

    op.drop_table('integration_nonces')
    with op.batch_alter_table('integration_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integration_events_expires_at'))

    op.drop_table('integration_events')
    # ### end Alembic commands ###
